import type { BookSchema } from "~/util/schema/book-schema";

const totalBooks = 50;
const bookTitles = [
  "The Great Gatsby",
  "To Kill a Mockingbird",
  "1984",
  "Pride and Prejudice",
  "The Catcher in the Rye",
  "The Lord of the Rings",
  "The Hobbit",
  "Harry Potter and the Sorcerer's Stone",
  "Fahrenheit 451",
  "Brave New World",
  "The Chronicles of Narnia",
  "Animal Farm",
  "The Grapes of Wrath",
  "Moby Dick",
  "War and Peace",
  "The Odyssey",
  "The Iliad",
  "Crime and Punishment",
  "The Brothers Karamazov",
  "Don Quixote",
  "Ulysses",
  "The Sound and the Fury",
  "As I Lay Dying",
  "One Hundred Years of Solitude",
  "Love in the Time of Cholera",
  "The Alchemist",
  "The Kite Runner",
  "A Thousand Splendid Suns",
  "The Help",
  "The Girl with the Dragon Tattoo",
  "The Hunger Games",
  "Divergent",
  "The Maze Runner",
  "Gone Girl",
  "The Da Vinci Code",
  "Angels & Demons",
  "The Shining",
  "It",
  "Misery",
  "The Stand",
  "Dracula",
  "Frankenstein",
  "The Picture of Dorian Gray",
  "Jane Eyre",
  "Wuthering Heights",
  "Great Expectations",
  "A Tale of Two Cities",
  "David Copperfield",
  "Oliver Twist",
  "Les Misérables",
];

export const BOOKS: BookSchema[] = Array.from(
  { length: totalBooks },
  (_, i) => {
    return {
      id: crypto.randomUUID(),
      title: bookTitles[i],
      author: "John Doe",
      published_year: "2020",
      genre: "Fiction",
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    };
  }
);
